# Generated by Django 5.0 on 2024-03-29 03:16

import protoAuth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0023_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=protoAuth.models.user_directory_path),
        ),
    ]
