# Generated by Django 5.0 on 2024-04-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0027_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contactAddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
