# Generated by Django 5.0 on 2024-05-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protoAuth', '0030_job_applications_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applications_count',
        ),
    ]
